kind: Service
apiVersion: v1
metadata:
  name: postgresql-service
spec:
  ports:
    - name: tcp-postgresql
      protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app.kubernetes.io/instance: kong
    app.kubernetes.io/name: postgresql
  type: LoadBalancer
---
