kind: Service
apiVersion: v1
metadata:
  name: postgresql-service
spec:
  ports:
    - name: tcp-postgresql
      protocol: TCP
      port: 5432
      targetPort: tcp-postgresql
  selector:
    app.kubernetes.io/instance: kong
    app.kubernetes.io/name: postgresql
  type: LoadBalancer
---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: postgresql-ingress
#   namespace: adminer
#   annotations:
#     nginx.ingress.kubernetes.io/proxy-body-size: 8m
#     nginx.ingress.kubernetes.io/proxy-connect-timeout: "500"
#     nginx.ingress.kubernetes.io/proxy-read-timeout: "500"
#     nginx.ingress.kubernetes.io/proxy-send-timeout: "500"
#     kubernetes.io/ingress.class: nginx
#     nginx.ingress.kubernetes.io/use-regex: "true"
# spec:
#   rules:
#   - host: postgresql.sorteiofire.com.br
#     http:
#       paths:
#       - pathType: Prefix
#         path: /
#         backend:
#           service:
#             name: kong-postgresql
#             port:
#               number: 5432
